<?php

/**
 * Implements hook_theme()
 */

 function retirement_calculator_theme($existing, $type, $theme, $path) {
    return [
        'retirement_form' => [
            'render element' => 'form',
        ],
    ];
 }
 
/**
 * Implements hook_mail()
 */

function retirement_calculator_mail($key, &$message, $params) {

    switch($key) {
        case 'retirement_results':
            $message['from'] = 'admin@backend.ddev.site';
            $message['subject'] = t($params['retirement_user'] . ": Projected Retirement Results");
            $message['body'][] = $params['message'];

            break;
    }
}